# Generated by Django 2.2.8 on 2020-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0041_auto_20200126_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
