# Generated by Django 2.2.8 on 2020-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0042_liste_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='validee',
            field=models.BooleanField(default=True),
        ),
    ]
