# Generated by Django 2.2.8 on 2020-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0043_liste_validee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('lienPhoto', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='liste',
            name='chartes',
            field=models.ManyToManyField(related_name='liste', to='compare.Charte'),
        ),
    ]
