# Generated by Django 2.2.8 on 2020-02-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0044_auto_20200213_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='traite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='critere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='chartes',
            field=models.ManyToManyField(blank=True, related_name='liste', to='compare.Charte'),
        ),
    ]
