# Generated by Django 2.2.8 on 2020-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0045_auto_20200225_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='charte',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
