# Generated by Django 2.2.8 on 2020-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0046_charte_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='charte',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
