# Generated by Django 2.2.8 on 2020-03-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0047_charte_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='liste',
            name='secondTour',
            field=models.BooleanField(default=True),
        ),
    ]
