# Generated by Django 2.2.8 on 2020-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0048_auto_20200313_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='elu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liste',
            name='scoreInscrit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='liste',
            name='scoreVoix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='AbstentionPremierTour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='codeCommune',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='nbInscrits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='votesBlancPremierTour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='votesNulsPremierTour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
