# Generated by Django 2.2.8 on 2020-06-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0049_auto_20200324_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='fusionAvec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Liste'),
        ),
    ]
